data:
  month_count: 24
  processed_path: ./data/ckd_data/processed/ckd_merged_data_for_modeling.csv
  raw_path: ./data/ckd_data/raw/
hyperparameters:
  batch_size:
  - 128
  dropout:
  - 0.0
  - 0.2
  - 0.4
  emb_dim:
  - 16
  - 32
  - 64
  hidden_dim:
  - 32
  - 64
  - 128
  learning_rate:
  - 0.001
  - 0.0001
  num_heads:
  - 2
  - 4
  - 8
  num_layers:
  - 2
  - 4
  - 6
model:
  type: coi
  batch_size: 128
  device: cpu
  dropout: 0.2
  emb_dim: 64
  hidden_dim: 128
  input_dim: 37
  learning_rate: 0.001
  max_seq_len: 50
  n_epochs: 500
  output_dim: 1
  patience: 7
  # CoI specific parameters
  num_heads: 4
  num_layers: 4
  alpha_init: 0.8
paths:
  results_path: ./results/ckd/
  save_path: ./results/ckd/
tuning:
  n_epochs: 500 